/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.torrentz.app;

import static br.com.torrentz.generic.GenMensagem.*;
import static br.com.torrentz.bll.BllRedefinirSenha.*;
import br.com.torrentz.bll.BllUsuario;
import br.com.torrentz.model.Usuario;
import java.util.ArrayList;

/**
 *
 * @author vovolinux
 */
public class AppRedefinirSenha extends javax.swing.JDialog {

    private String email = "";
    private String codigo = "";
    private Usuario usuario = null;
    private ArrayList<Usuario> usuarios = null;

    public void setUsuarios(ArrayList<Usuario> usuarios) {
        this.usuarios = usuarios;
    }

    /**
     * Creates new form AppRedefinir
     */
    public AppRedefinirSenha(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.setTitle("Redefinir Senha");
        email = "";
        codigo = "";
        usuario = null;
        jTextFieldEmail.setVisible(true);
        jTextFieldCodigo.setVisible(false);
        jPasswordField.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRedefinir = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();
        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelInstrucao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonRedefinir.setText("Redefinir");
        jButtonRedefinir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRedefinirActionPerformed(evt);
            }
        });

        jTextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyReleased(evt);
            }
        });

        jLabelInstrucao.setText("Informe seu e-mail");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonRedefinir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelInstrucao)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelInstrucao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRedefinir)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRedefinirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRedefinirActionPerformed
        try {
            switch (jButtonRedefinir.getText()) {
                case "Redefinir":
                    if (emailValido(jTextFieldEmail.getText())) {
                        email = jTextFieldEmail.getText().trim();
                        codigo = redefinir(email, usuarios);
                        usuario = getUsuario();
                        jLabelInstrucao.setText("Informe o código de verificação");
                        jTextFieldEmail.setVisible(false);
                        jTextFieldCodigo.setVisible(true);
                        jPasswordField.setVisible(false);
                        jButtonRedefinir.setText("Verificar");
                        jTextFieldCodigo.requestFocus();
                    }
                    break;

                case "Verificar":
                    if (jTextFieldCodigo.getText().trim().equalsIgnoreCase(codigo)) {
                        jLabelInstrucao.setText("Informe sua nova senha");
                        jTextFieldEmail.setVisible(false);
                        jTextFieldCodigo.setVisible(false);
                        jPasswordField.setVisible(true);
                        jButtonRedefinir.setText("Confirmar");
                        jPasswordField.requestFocus();
                    } else {
                        throw new Exception("Código de verificação não confere com o enviado por e-mail!");
                    }
                    break;
                case "Confirmar":
                    if (usuario != null) {
                        usuario.setSenha(new String(jPasswordField.getPassword()));
                        new BllUsuario().update(usuario);
                        mensagem("Sucesso!", "Sua senha foi redefinida com sucesso!");
                        this.setVisible(false);
                    }
                    break;
            }
        } catch (Exception e) {
            mensagemErro(e);
        }
    }//GEN-LAST:event_jButtonRedefinirActionPerformed

    private void jTextFieldEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyReleased
        try{ 
            jTextFieldEmail.setText(jTextFieldEmail.getText().toLowerCase());
        } catch (Exception e) {
            mensagemErro(e);
        }
    }//GEN-LAST:event_jTextFieldEmailKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppRedefinirSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppRedefinirSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppRedefinirSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppRedefinirSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AppRedefinirSenha dialog = new AppRedefinirSenha(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRedefinir;
    private javax.swing.JLabel jLabelInstrucao;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldCodigo;
    public javax.swing.JTextField jTextFieldEmail;
    // End of variables declaration//GEN-END:variables
}
